import os
from langchain_openai import ChatOpenAI
import re # For parsing questions
from typing import List # For type hinting
from langchain_core.prompts import ChatPromptTemplate
# Removed BaseLangChainError import
# It's good practice to also be aware of specific OpenAI errors,
# though LangChain might wrap them.
from openai import APIError, RateLimitError, AuthenticationError, APITimeoutError, APIConnectionError


from brd.prompts import (
    STRATA_BRD_PRO_PERSONA,
    INITIAL_BRD_SECTIONS_TASK_TEMPLATE,
    CLARIFICATION_QUESTIONS_TEMPLATE,
    REFINE_UNDERSTANDING_TEMPLATE # New import
)

# Initialize the LLM
if not os.getenv("OPENAI_API_KEY"):
    print("Warning: OPENAI_API_KEY not found in environment. LLM calls will fail.")

# TODO: Experiment with more advanced models (e.g., GPT-4) and temperature settings
#       as the agent matures. Consider making these configurable.
llm = None
if os.getenv("OPENAI_API_KEY"):
    llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.7)
else:
    print("Warning: LLM not initialized due to missing OPENAI_API_KEY. Operations requiring LLM will use placeholder data or fail gracefully if not handled.")

# TODO: In a production setting, consider adding retry logic (e.g., using the 'tenacity' library)
#       for LLM calls to handle transient network issues or temporary API unavailability.

def generate_initial_brd_sections(user_input: str) -> str:
    """
    Generates a subset of BRD sections based on user input and the StrataBRD Pro persona.
    Focuses on: Executive Summary, Vision & Scope, and a basic Functional Requirements structure.
    """
    if not llm:
        # OPENAI_API_KEY was not set, llm was not initialized.
        # Return a structured message indicating this, for structural verification.
        print("--- LLM not available (OPENAI_API_KEY missing). Returning structural template. ---")
        # Extract section headers from INITIAL_BRD_SECTIONS_TASK_TEMPLATE to show structure
        # This is a simplified way to get them for this specific verification task.
        # A more robust way might involve parsing the template if it were more complex.
        sections_to_generate_header = "SECTIONS TO GENERATE:"
        start_index = INITIAL_BRD_SECTIONS_TASK_TEMPLATE.find(sections_to_generate_header)
        sections_text = ""
        if start_index != -1:
            sections_text = INITIAL_BRD_SECTIONS_TASK_TEMPLATE[start_index + len(sections_to_generate_header):].strip()
            # Replace the example part for functional requirements for cleaner structural view
            fr_example_text = """\
    *   Example:
        *   **FR-001: [User Story Title]**
            *   As a [type of user], I want [an action] so that [a benefit/value].
            *   **Acceptance Criteria:**
                *   Criterion 1.
                *   Criterion 2."""
            sections_text = sections_text.replace(fr_example_text, "    *   [Functional Requirements details would be generated here]")


        return f"""
Error: OPENAI_API_KEY not set. LLM not called.
This is a placeholder output to verify structure.
Based on your input: "{user_input[:100]}..."

Expected sections to be generated by the LLM:
{sections_text}
"""

    print(f"--- Calling LLM for BRD Generation with input: {user_input[:100]}... ---")

    try:
        prompt_template = ChatPromptTemplate.from_messages([
            ("system", STRATA_BRD_PRO_PERSONA),
            ("human", INITIAL_BRD_SECTIONS_TASK_TEMPLATE)
        ])

        chain = prompt_template | llm
        response = chain.invoke({"user_input": user_input})

        generated_content = response.content
        print("--- LLM Response Received ---")
        return generated_content
    # Specific OpenAI errors
    except APIError as e: # Catching the base OpenAI error
        error_type = type(e).__name__
        print(f"OpenAI API Error during LLM call ({error_type}): {e}")

        # Check for specific OpenAI error types
        if isinstance(e, AuthenticationError):
            return "Error: LLM authentication failed. Please check your API key."
        elif isinstance(e, RateLimitError):
            return "Error: LLM rate limit exceeded. Please try again later or check your plan."
        elif isinstance(e, (APITimeoutError, APIConnectionError)):
            return "Error: LLM connection issue. Please check your network or try again later."
        else: # General APIError that isn't more specific from the ones above
            return f"Error: An OpenAI API issue occurred while generating BRD content ({error_type})."
    # Catch other potential errors that could be LangChain related or other unexpected issues
    except Exception as e:
        error_type = type(e).__name__
        # Check if it's an error from LangChain by looking for 'langchain' in module name, if possible
        module = getattr(type(e), '__module__', '')
        if 'langchain' in module: # or 'langgraph' or other related ones
            print(f"LangChain related error during LLM call ({error_type}): {e}")
            return f"Error: A LangChain operation failed while generating BRD content ({error_type})."
        else:
            print(f"An unexpected error occurred during LLM call ({error_type}): {e}")
            return "Error: An unexpected issue occurred while generating BRD content."


def get_clarification_questions(current_project_summary: str, latest_user_utterance: str) -> List[str]:
    """
    Analyzes the current project summary and latest user utterance to determine if clarification
    questions are needed to draft a comprehensive BRD.
    Returns a list of questions or an empty list if no questions are needed.
    """
    if not llm:
        print("--- LLM not available (OPENAI_API_KEY missing). Skipping clarification question generation. ---")
        # Return a default question or empty list if no LLM. For now, empty.
        # Could also return a fixed question like ["What are the primary goals for this project?"]
        return []

    print(f"--- Calling LLM for Clarification Questions. Summary: '{current_project_summary[:100]}...', Utterance: '{latest_user_utterance[:100]}...' ---")

    try:
        prompt_template = ChatPromptTemplate.from_messages([
            ("system", STRATA_BRD_PRO_PERSONA),
            ("human", CLARIFICATION_QUESTIONS_TEMPLATE)
        ])

        chain = prompt_template | llm
        response = chain.invoke({
            "current_project_summary": current_project_summary,
            "latest_user_utterance": latest_user_utterance
        })

        response_content = response.content.strip()
        print(f"--- LLM Response for Clarification Questions: ---\n{response_content}")

        if response_content == "NO_QUESTIONS_NEEDED":
            return []

        questions_found = []
        raw_lines = response_content.splitlines()
        for line in raw_lines:
            original_line_stripped = line.strip()
            if not original_line_stripped: # Skip empty or whitespace-only lines
                continue

            # Attempt to strip common list markers
            cleaned_line = re.sub(r"^\s*(\d+[\.\)]\s*|-\s*)", "", original_line_stripped).strip()

            # Add to questions if the line after stripping is non-empty AND
            # (it was actually changed by stripping a marker OR it's a single-line response from LLM)
            # The latter part (single-line response) is tricky; for now, we are strict:
            # only add if a marker was visibly stripped or it's a very simple case.
            # The prompt asks for a numbered list. If it's not, it's "malformed" or needs more robust parsing.
            # For current tests, we require a marker to be stripped for a line to be a question,
            # unless it's the *only* line of response.
            if cleaned_line and cleaned_line != original_line_stripped: # Only add if a marker was stripped
                questions_found.append(cleaned_line)

        # If after trying to parse, no questions were found, AND the response wasn't the specific "NO_QUESTIONS_NEEDED" marker
        if not questions_found and response_content != "NO_QUESTIONS_NEEDED":
             print(f"Warning: Clarification LLM response was not 'NO_QUESTIONS_NEEDED' and no questions with valid markers could be parsed. Response: {response_content}")
             return []

        return questions_found

    except APIError as e:
        error_type = type(e).__name__
        print(f"OpenAI API Error during clarification LLM call ({error_type}): {e}")
        # Fallback to empty list or default question
        return []
    except Exception as e:
        error_type = type(e).__name__
        module = getattr(type(e), '__module__', '')
        if 'langchain' in module:
            print(f"LangChain related error during clarification LLM call ({error_type}): {e}")
        else:
            print(f"An unexpected error occurred during clarification LLM call ({error_type}): {e}")
        # Fallback to empty list or default question
        return []


def refine_project_understanding(current_summary: str, questions_asked: List[str], user_answers: str) -> str:
    """
    Refines the project understanding by synthesizing the current summary, questions asked,
    and user's answers into a new, coherent summary.
    Returns the revised project summary.
    """
    if not llm:
        print("--- LLM not available (OPENAI_API_KEY missing). Skipping project understanding refinement. ---")
        # Return the original summary if LLM is not available
        return current_summary

    print(f"--- Calling LLM for Project Understanding Refinement. ---")
    print(f"  Current Summary: '{current_summary[:100]}...'")
    # Format questions for the prompt
    formatted_questions = "\n".join([f"{i+1}. {q}" for i, q in enumerate(questions_asked)])
    print(f"  Questions Asked:\n{formatted_questions}")
    print(f"  User Answers: '{user_answers[:100]}...'")

    try:
        prompt_template = ChatPromptTemplate.from_messages([
            ("system", STRATA_BRD_PRO_PERSONA),
            ("human", REFINE_UNDERSTANDING_TEMPLATE)
        ])

        chain = prompt_template | llm
        response = chain.invoke({
            "current_project_summary": current_summary,
            "questions_that_were_asked": formatted_questions,
            "user_answers": user_answers
        })

        revised_summary = response.content.strip()
        print(f"--- LLM Response for Refined Summary: ---\n{revised_summary[:300]}...")
        return revised_summary

    except APIError as e:
        error_type = type(e).__name__
        print(f"OpenAI API Error during understanding refinement LLM call ({error_type}): {e}")
        return current_summary # Fallback to original summary
    except Exception as e:
        error_type = type(e).__name__
        module = getattr(type(e), '__module__', '')
        if 'langchain' in module:
            print(f"LangChain related error during understanding refinement LLM call ({error_type}): {e}")
        else:
            print(f"An unexpected error occurred during understanding refinement LLM call ({error_type}): {e}")
        return current_summary # Fallback to original summary


if __name__ == '__main__':
    print("Testing BRD generation function...")
    # Simplified main guard for direct testing of generate_initial_brd_sections
    # The full main.py handles .env loading now.
    api_key_present = bool(os.getenv("OPENAI_API_KEY"))
    print(f"OpenAI API Key Present: {api_key_present}")

    if not api_key_present:
        print("OPENAI_API_KEY not found. `generate_initial_brd_sections` will return placeholder.")
        print("Skipping `get_clarification_questions` and `refine_project_understanding` tests as they require LLM.")
    else:
        print("\nTesting clarification question generation...")
        summary_test_cq = "The user wants a new e-commerce platform."
        utterance_test_cq = "It should sell books and support credit card payments. We need to target young adults."
        questions = get_clarification_questions(summary_test_cq, utterance_test_cq)
        if questions:
            print("Generated Clarification Questions:")
            for q_idx, q_text in enumerate(questions):
                print(f"- {q_text}")

            print("\nTesting project understanding refinement...")
            # Simulate some answers
            answers_test = "1. The primary goal is to increase online book sales by 20% within the first year. 2. Yes, Stripe for payments."
            if len(questions) > 2 : # if LLM gave 3 questions, provide a generic 3rd answer
                answers_test += " 3. We also need a mobile app for iOS and Android."

            refined_summary = refine_project_understanding(
                current_summary=utterance_test_cq, # Using utterance as initial summary for this test flow
                questions_asked=questions,
                user_answers=answers_test
            )
            print(f"\nInitial Summary was: {utterance_test_cq}")
            print(f"Refined Summary is: {refined_summary}")

        elif not questions: # Handles empty list specifically
             print("LLM indicated no clarification questions are needed for the initial input.")
        # else case for unexpected type from get_clarification_questions is not strictly needed due to type hints


    sample_input_for_test = "Develop an AI-powered chatbot for customer service that can handle product returns and answer FAQs."
    brd_output = generate_initial_brd_sections(sample_input_for_test)
    print("\n--- generate_initial_brd_sections Output ---")
    print(brd_output)
    print("--- End of Test ---")
