import os
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
# Removed BaseLangChainError import
# It's good practice to also be aware of specific OpenAI errors,
# though LangChain might wrap them.
from openai import APIError, RateLimitError, AuthenticationError, APITimeoutError, APIConnectionError


from brd.prompts import STRATA_BRD_PRO_PERSONA, INITIAL_BRD_SECTIONS_TASK_TEMPLATE

# Initialize the LLM
if not os.getenv("OPENAI_API_KEY"):
    print("Warning: OPENAI_API_KEY not found in environment. LLM calls will fail.")

# TODO: Experiment with more advanced models (e.g., GPT-4) and temperature settings
#       as the agent matures. Consider making these configurable.
llm = None
if os.getenv("OPENAI_API_KEY"):
    llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.7)
else:
    print("Warning: LLM not initialized due to missing OPENAI_API_KEY. Operations requiring LLM will use placeholder data or fail gracefully if not handled.")

# TODO: In a production setting, consider adding retry logic (e.g., using the 'tenacity' library)
#       for LLM calls to handle transient network issues or temporary API unavailability.

def generate_initial_brd_sections(user_input: str) -> str:
    """
    Generates a subset of BRD sections based on user input and the StrataBRD Pro persona.
    Focuses on: Executive Summary, Vision & Scope, and a basic Functional Requirements structure.
    """
    if not llm:
        # OPENAI_API_KEY was not set, llm was not initialized.
        # Return a structured message indicating this, for structural verification.
        print("--- LLM not available (OPENAI_API_KEY missing). Returning structural template. ---")
        # Extract section headers from INITIAL_BRD_SECTIONS_TASK_TEMPLATE to show structure
        # This is a simplified way to get them for this specific verification task.
        # A more robust way might involve parsing the template if it were more complex.
        sections_to_generate_header = "SECTIONS TO GENERATE:"
        start_index = INITIAL_BRD_SECTIONS_TASK_TEMPLATE.find(sections_to_generate_header)
        sections_text = ""
        if start_index != -1:
            sections_text = INITIAL_BRD_SECTIONS_TASK_TEMPLATE[start_index + len(sections_to_generate_header):].strip()
            # Replace the example part for functional requirements for cleaner structural view
            fr_example_text = """\
    *   Example:
        *   **FR-001: [User Story Title]**
            *   As a [type of user], I want [an action] so that [a benefit/value].
            *   **Acceptance Criteria:**
                *   Criterion 1.
                *   Criterion 2."""
            sections_text = sections_text.replace(fr_example_text, "    *   [Functional Requirements details would be generated here]")


        return f"""
Error: OPENAI_API_KEY not set. LLM not called.
This is a placeholder output to verify structure.
Based on your input: "{user_input[:100]}..."

Expected sections to be generated by the LLM:
{sections_text}
"""

    print(f"--- Calling LLM for BRD Generation with input: {user_input[:100]}... ---")

    try:
        prompt_template = ChatPromptTemplate.from_messages([
            ("system", STRATA_BRD_PRO_PERSONA),
            ("human", INITIAL_BRD_SECTIONS_TASK_TEMPLATE)
        ])

        chain = prompt_template | llm
        response = chain.invoke({"user_input": user_input})

        generated_content = response.content
        print("--- LLM Response Received ---")
        return generated_content
    # Specific OpenAI errors
    except APIError as e: # Catching the base OpenAI error
        error_type = type(e).__name__
        print(f"OpenAI API Error during LLM call ({error_type}): {e}")

        # Check for specific OpenAI error types
        if isinstance(e, AuthenticationError):
            return "Error: LLM authentication failed. Please check your API key."
        elif isinstance(e, RateLimitError):
            return "Error: LLM rate limit exceeded. Please try again later or check your plan."
        elif isinstance(e, (APITimeoutError, APIConnectionError)):
            return "Error: LLM connection issue. Please check your network or try again later."
        else: # General APIError that isn't more specific from the ones above
            return f"Error: An OpenAI API issue occurred while generating BRD content ({error_type})."
    # Catch other potential errors that could be LangChain related or other unexpected issues
    except Exception as e:
        error_type = type(e).__name__
        # Check if it's an error from LangChain by looking for 'langchain' in module name, if possible
        module = getattr(type(e), '__module__', '')
        if 'langchain' in module: # or 'langgraph' or other related ones
            print(f"LangChain related error during LLM call ({error_type}): {e}")
            return f"Error: A LangChain operation failed while generating BRD content ({error_type})."
        else:
            print(f"An unexpected error occurred during LLM call ({error_type}): {e}")
            return "Error: An unexpected issue occurred while generating BRD content."

if __name__ == '__main__':
    print("Testing BRD generation function...")
    # Simplified main guard for direct testing of generate_initial_brd_sections
    # The full main.py handles .env loading now.
    api_key_present = bool(os.getenv("OPENAI_API_KEY"))
    print(f"OpenAI API Key Present: {api_key_present}")

    if not api_key_present:
        print("OPENAI_API_KEY not found. `generate_initial_brd_sections` will return placeholder.")

    sample_input_for_test = "Develop an AI-powered chatbot for customer service that can handle product returns and answer FAQs."
    brd_output = generate_initial_brd_sections(sample_input_for_test)
    print("\n--- generate_initial_brd_sections Output ---")
    print(brd_output)
    print("--- End of Test ---")
